name: Render video
on:
  workflow_dispatch:
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - run: pnpm install
      - run: pnpm exec remotion render MyVideo out/my-video.mp4
      - uses: actions/upload-artifact@v4
        with:
          name: my-video.mp4
          path: out/my-video.mp4
